name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - ga
          - prod
        default: 'dev'
      action:
        description: 'Terraform Action (plan or apply)'
        required: true
        type: choice
        options:
          - plan
          - apply
        default: 'plan'

jobs:
  deploy:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # AWS CLI Login (for Route 53)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      # Terraform Init
      - name: Terraform Init
        run: |
          cd platform-api
          terraform init -backend-config="backend-configs/${{ inputs.environment }}.backend.tfvars" -reconfigure

      # Terraform Plan (if selected)
      - name: Terraform Plan
        if: ${{ inputs.action == 'plan' }}
        run: |
          cd platform-api
          terraform plan -var="env=${{ inputs.environment }}"

      # Terraform Apply (if selected)
      - name: Terraform Apply
        if: ${{ inputs.action == 'apply' }}
        run: |
          cd platform-api
          terraform apply -var="env=${{ inputs.environment }}" -auto-approve
